export const ADD_INGREDIENT = 'ADDINGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVEINGREDIENT';
export const SET_INGREDIENT = 'SET_INGREDIENT';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';